# Generated by Django 3.0.8 on 2020-08-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlists',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='auctions.active_list'),
        ),
    ]
