# Generated by Django 3.0.8 on 2020-08-12 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200810_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bidded_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bidding', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='closed_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed', to='auctions.active_list')),
                ('won_bid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed_bid', to='auctions.bids')),
            ],
        ),
    ]
