# Generated by Django 3.0.8 on 2020-08-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200812_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_list',
            name='image',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/600px-No_image_available.svg.png'),
        ),
    ]
