# Generated by Django 3.0.8 on 2020-08-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200812_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_list',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='closed_list',
        ),
    ]
