# Generated by Django 3.0.8 on 2020-08-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200812_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_list',
            name='won_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='won', to='auctions.bids'),
            preserve_default=False,
        ),
    ]
