# Generated by Django 3.0.8 on 2020-08-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_active_list_won_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_list',
            name='won_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='won', to='auctions.bids'),
        ),
    ]
