# Generated by Django 3.0.8 on 2020-08-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200813_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_list',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='auctions.groups'),
        ),
    ]
